"/**":
  ros__parameters:
    camera:
      #i_enable_imu: false
      i_ip: "192.168.69.9"
      i_mx_id: "14442C107111D1D600"
      i_nn_type: "NONE"
      i_pipeline_type: "RGB"
      i_tf_base_frame: "oak"
      i_tf_cam_pitch: "0.0"
      i_tf_cam_pos_x: "0.0"
      i_tf_cam_pos_y: "0.0"
      i_tf_cam_pos_z: "0.0"
      i_tf_cam_roll: "0.0"
      i_tf_cam_yaw: "0.0"
      i_tf_camera_model: ""
      i_tf_camera_name: "oak"
      i_tf_custom_urdf_location: ""
      i_tf_custom_xacro_args: ""
      #i_tf_imu_from_descr: "false"
      i_tf_parent_frame: "roof_camera_link"
    rgb:
      i_add_exposure_offset: false
      i_enable_feature_tracker: false
      i_enable_lazy_publisher: true
      i_enable_nn: false
      i_enable_preview: false
      i_exposure_offset: 0
      i_fps: 15.0
      i_fsync_continuous: false
      i_fsync_trigger: false
      i_get_base_device_timestamp: false
      i_isp_den: 3
      i_isp_num: 2
      i_keep_preview_aspect_ratio: true
      i_low_bandwidth: false
      i_low_bandwidth_quality: 90
      i_max_q_size: 30
      i_output_isp: true
      i_publish_topic: true
      i_resolution: "1080P"
      i_sensor_img_orientation: "AUTO"
      i_update_ros_base_time_on_ros_msg: false
