 #############################################################################
 #                            _     _     _     _                            #
 #                           / \   / \   / \   / \                           #
 #                          ( O ) ( L ) ( A ) ( V )                          #
 #                           \_/   \_/   \_/   \_/                           #
 #                                                                           #
 #                  OLAV: Off-Road Light Autonomous Vehicle                  #
 #############################################################################

# A service to set the inputs, outputs and switching logic for the
# drive-by-wire.

# Enumeration type for the control mode.
#
# The following types are available:
#
# - (-1) STANDBY
#
# - (+0) DRIVE_ACKERMANN
#
# - (+1) DRIVE_TBS

int8 MODE_STANDBY = -1
int8 MODE_DRIVE_ACKERMANN = 0
int8 MODE_DRIVE_TBS = 1

#

int8 AUTHORITHY_SYSTEM = -1
int8 AUTHORITHY_TERMINAL = 0
int8 AUTHORITHY_GAMEPAD = 1
int8 AUTHORITHY_AUTONOMY = 2

# REQUEST
# -------

# Target control mode
int8 mode
int8 authority

---

# RESULT
# ------

# Whether or not the drive-by-wire switched to the target control mode.
bool success

# Status information or error message.
string message