 #############################################################################
 #                            _     _     _     _                            #
 #                           / \   / \   / \   / \                           #
 #                          ( O ) ( L ) ( A ) ( V )                          #
 #                           \_/   \_/   \_/   \_/                           #
 #                                                                           #
 #                  OLAV: Off-Road Light Autonomous Vehicle                  #
 #############################################################################

# This service instructs the drive-by-wire system to activate the engine starter
# for a given amount of time, simulating the act of turning the key from the
# ignition to the starter position.

# REQUEST
# -------

# Empty request data.
float64 duration

---

# RESULT
# ------

# Outcome of the engine start attempt.
bool success

# In case of failure, details on the error state.
string message