"/**":
  ros__parameters:
    limits:
      warn: true
      strict: true
      efforts:
        throttle: 1.0
        brake: 1.0
        steering: 1.0
      setpoint:
        speed: 4.17
        steering_angle: 0.576
    initial_mode: "manual"
