"/**":
  ros__parameters:
    olav:
      pub_rate: 2.0
      type: diagnostic_aggregator/AnalyzerGroup
      path: olav
      analyzers:
        drive-by-wire:
          type: diagnostic_aggregator/GenericAnalyzer
          path: drive-by-wire
          startswith: ["olav/drive-by-wire/"]
          find_and_remove_prefix: ["olav/drive-by-wire"]
        powertrain:
          type: diagnostic_aggregator/GenericAnalyzer
          path: powertrain
          startswith: ["olav/powertrain/"]
          find_and_remove_prefix: ["olav/powertrain"]
