"/**":
  ros__parameters:
    rate: 100.0
    pid:
      gains:
        feedforward: 0.0
        proportional: 0.05
        integral: 0.00045
        derivative: 0.0
      setpoint:
        ramp:
          enabled: true
          magnitude: 0.01
      output:
        change:
          enabled: false
          magnitude: 0.1
      limit:
        integral:
          enabled: true
          magnitude: 0.4
      feedforward:
        offset:
          positive: 0.18
          negative: 0.18
      deadband:
        filter:
          enabled: true
          thresholds:
            lower: -0.225
            upper: 0.225
    brake:
      enabled: false
      threshold: 0.3
      limit: 0.5
