"/**":
  ros__parameters:
    rate: 100.0
    pid:
      feedforward:
        offset: 0.3
      gains:
        proportional: 1.5
        integral: 0.004
        derivative: 0.2
      setpoint:
        ramp:
          enabled: true
          magnitude: 0.04
      output:
        minimum: -1.0
        maximum: 1.0
        change:
          enabled: false
          magnitude: 0.001
      limit:
        integral:
          enabled: false
          magnitude: 0.3
        error:
          enable: true
          magnitude: 0.02
      deadband:
        filter:
          enabled: false
          thresholds:
            lower: -0.3
            upper: 0.3
