"/**":
  ros__parameters:
    controller:
      rate: 100.0
      gains:
        proportional: 0.05
        integral: 0.005
        derivative: 0.0
      setpoint:
        ramp:
          enabled: true
          magnitude: 0.2
      output:
        minimum: -1.0
        maximum: 1.0
        change:
          enabled: true
          magnitude: 0.001
      limit:
        integral:
          enabled: true
          magnitude: 0.3
      deadband:
        filter:
          enabled: false
          thresholds:
            lower: -0.3
            upper: 0.3
